version: '3'
services:
  couchdb-for-ols:
    image: couchdb
    container_name: couchdb-for-ols
    restart: always
    environment:
      - COUCHDB_USER=${username}
      - COUCHDB_PASSWORD=${password}
    volumes:
      - ${PWD}/couchdb-data:/opt/couchdb/data
      - ${PWD}/couchdb-etc:/opt/couchdb/etc/local.d
    ports:
      - 5984:5984